In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## `pandas` settings
Make it so that we can see long lists, because we have a lot of potential features.

In [24]:
pd.options.display.max_seq_items = 2000 # default is 100
pd.options.display.max_columns = 250 # default is 20
pd.options.display.max_rows = 250 # default is 20

# Data processing

We need to prepare the dataset for use in modeling. (Dataset originally compiled using GIS.)

In [56]:
df = pd.read_csv('data/Final Dataset.csv', skipinitialspace=True)
# df.replace(r'\s+', np.nan, inplace=True, regex=True)
df.head()

/home/carlin/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (18,19,32,80,85,226,227) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


FID  FID_1  FID_1_1  OBJECTID  REC RIA_RTE_ID  RTE_GRID   GID  FRM_DFO  \
0    0    319      319       320    1  FM0619-KG    175724  3134    4.764   
1    1    579      579       580    1  FM0619-KG    175724  3134    3.708   
2    2    596      596       597    1  FM0583-KG    175685  3090    9.283   
3    3    513      513       514    1  FM0541-KG    175640  3038   34.630   
4    4    330      330       331    1  FM0523-KG    175622  3014   12.785   

   TO_DFO    C_SEC     CON  SEC     BMP     EMP  RI_MPT_DAT     HWY HSYS HNUM  \
0   4.957  0986-03   986.0    3   4.783   4.977      201505  FM0619   FM  619   
1   3.729  0986-03   986.0    3   3.723   3.744      201505  FM0619   FM  619   
2   9.287  1033-02  1033.0    2   7.816   7.820      201505  FM0583   FM  583   
3  34.648  0366-09   366.0    9   9.415   9.433      201505  FM0541   FM  541   
4  12.814  1003-01  1003.0    1  15.007  15.036      201505  FM0523   FM  523   

  HSUF RDBD_ID  FRM_NBR FRM_SUF FRM_NUM  FRM_DISP  TO_NBR TO_SUF TO_NUM  \
0  NaN      CG      418     NaN     418     0.764     418    NaN    418   
1  NaN      CG      416     NaN     416     1.708     416    NaN    416   
2  NaN      CG      324     NaN     324     1.805     324    NaN    324   
3  NaN      CG      556     NaN     556     1.905     556    NaN    556   
4  NaN      CG      516     NaN     516     1.072     516    NaN    516   

   TO_DISP  FRM_MKR_DA  TO_MKR_DAT  DIR_TRAV STE_NAM  DI   CO   CITY  MPA  \
0    0.957    20150512    20150512         1     NaN  14  246  41900   90   
1    1.729    20150512    20150512         1     NaN  14  246      0   90   
2    1.809    20150512    20150512         4     NaN  23   25      0    0   
3    1.923    20150512    20150512         4     NaN  15  247      0    0   
4    1.101    20150512    20150512         1     NaN  12   20      0   15   

   UAN  UAN_HPMS  RU  MSA_CNTY  MAINT_DIS  MNT_SEC  PBLC_LAND  ADMIN  \
0    0         0   1         1         14       13        NaN      1   
1    0         0   1         1         14       13        NaN      1   
2    0         0   1         0         23        1        NaN      1   
3    0         0   1         1         15        4        NaN      1   
4  459     46801   3         1         12        2        NaN      1   

   RDWAY_MAIN  F_SYSTEM RU_F_SYSTE  SEC_NHS  SEC_NHS_AP  SEC_STR  SEC_TRUNK  \
0           1         5         R5        0         NaN        0          0   
1           1         5         R5        0         NaN        0          0   
2           1         6         R6        0         NaN        0          0   
3           1         5         R5        0         NaN        0          0   
4           1         4         U4        0         NaN        0          0   

   SEC_TRK  SEC_EVAC  SEC_NFH  SEC_STM  SEC_TTT  SEC_PARK  SEC_BIC  SEC_ADP  \
0        0         0        0        0        0         0        0        0   
1        0         0        0        0        0         0        0        0   
2        0         0        0        0        0         0        0        0   
3        0         0        0        0        0         0        0        0   
4        0         1        0        0        0         0        0        0   

   SEC_FED_AI  MSA_CLS  TOP100ID  TOP_100_BE  TOP_100_EN  FRGHT_NTWR  \
0           1       11       NaN         NaN         NaN         NaN   
1           1       11       NaN         NaN         NaN         NaN   
2           0       11       NaN         NaN         NaN         NaN   
3           1       11       NaN         NaN         NaN         NaN   
4           1       11       NaN         NaN         NaN         NaN   

   HWY_STAT  HWY_STAT_D      DOTT  DCTT  CLSR_RESN  HWY_NOTE  SPD_MAX  \
0         6    19950429  19950429   NaN        NaN       NaN       60   
1         6    19950429  19950429   NaN        NaN       NaN       60   
2         6    19950429  19950429   NaN        NaN       NaN       60   
3         6    19950429  199504

In [57]:
df.columns

Index(['FID', 'FID_1', 'FID_1_1', 'OBJECTID', 'REC', 'RIA_RTE_ID', 'RTE_GRID',
       'GID', 'FRM_DFO', 'TO_DFO', 'C_SEC', 'CON', 'SEC', 'BMP', 'EMP',
       'RI_MPT_DAT', 'HWY', 'HSYS', 'HNUM', 'HSUF', 'RDBD_ID', 'FRM_NBR',
       'FRM_SUF', 'FRM_NUM', 'FRM_DISP', 'TO_NBR', 'TO_SUF', 'TO_NUM',
       'TO_DISP', 'FRM_MKR_DA', 'TO_MKR_DAT', 'DIR_TRAV', 'STE_NAM', 'DI',
       'CO', 'CITY', 'MPA', 'UAN', 'UAN_HPMS', 'RU', 'MSA_CNTY', 'MAINT_DIS',
       'MNT_SEC', 'PBLC_LAND', 'ADMIN', 'RDWAY_MAIN', 'F_SYSTEM', 'RU_F_SYSTE',
       'SEC_NHS', 'SEC_NHS_AP', 'SEC_STR', 'SEC_TRUNK', 'SEC_TRK', 'SEC_EVAC',
       'SEC_NFH', 'SEC_STM', 'SEC_TTT', 'SEC_PARK', 'SEC_BIC', 'SEC_ADP',
       'SEC_FED_AI', 'MSA_CLS', 'TOP100ID', 'TOP_100_BE', 'TOP_100_EN',
       'FRGHT_NTWR', 'HWY_STAT', 'HWY_STAT_D', 'DOTT', 'DCTT', 'CLSR_RESN',
       'HWY_NOTE', 'SPD_MAX', 'SPD_MIN', 'ALT_SPD_LM', 'ALT_SPD__1',
       'SCHOOL_ZN', 'LOAD_AXLE', 'LOAD_GROSS', 'LOAD_TAND', 'TOLL_NM', 'DBTP',
       'PEAK_DRCT_', '

## Dropping no-information columns

I get the feeling that there are a lot of columns with little to no information. We'll identify and filter out the ones that only have one or two unique values, or have a unique value for every data point (except for `FID`, which we'll keep as a unique identifier).

In [58]:
print("Total row count:", len(df.index))
cols_dropped = []
for col in df.columns:
    uniquecount = len(df[col].unique())
    if ((uniquecount == len(df.index)) or (uniquecount == 1)) and (col != 'FID'):
        print('{}\t\t{}'.format(col, uniquecount))
        cols_dropped.append(col)
df.drop(cols_dropped, axis=1, inplace=True)
print('Cols filtered:', len(cols_dropped))
print(cols_dropped)

Total row count: 156451
FID_1		156451
FID_1_1		156451
OBJECTID		156451
REC		1
RDBD_ID		1
SEC_TTT		1
SEC_PARK		1
TOP_100_BE		1
TOP_100_EN		1
FRGHT_NTWR		1
DCTT		1
CLSR_RESN		1
HWY_NOTE		1
SCHOOL_ZN		1
DBTP		1
PEAK_DRCT_		1
CAUSEWAY		1
TUNNEL		1
MULT_MOD_F		1
ADT_YEAR		1
ADT_HIST_Y		1
DESGN_YR		1
TRUCK_HY_1		1
TRUCK_HY_2		1
TRUCK_HY_3		1
TRUCK_HY_4		1
TRUCK_HY_5		1
TRUCK_HY_6		1
TRUCK_HY_7		1
TRUCK_HY_8		1
TRUCK_HY_9		1
B_TERM		1
E_TERM		1
PHY_RDBD		1
PEAK_LANE		1
CNTR_PEAK_		1
TRFC_SGNL		1
PCT_GREEN_		1
NBR_SGNL		1
NBR_STOP_S		1
ATGRD_OTHR		1
WIDE_OBST		1
WIDE_PTNTL		1
CURV_CLASS		1
CURV_CLA_1		1
CURV_CLA_2		1
CURV_CLA_3		1
CURV_CLA_4		1
CURV_CLA_5		1
VERT_GRADE		1
VERT_GRA_1		1
VERT_GRA_2		1
VERT_GRA_3		1
VERT_GRA_4		1
VERT_GRA_5		1
TRRN		1
PPSD		1
PSR		1
PSR_DT		1
RUTTING		1
FAULT		1
CRACK_PCT		1
CRACK_LNGT		1
CLMT_ZN		1
SOIL		1
LOC_ERROR		1
Cols filtered: 66
['FID_1', 'FID_1_1', 'OBJECTID', 'REC', 'RDBD_ID', 'SEC_TTT', 'SEC_PARK', 'TOP_100_BE', 'TOP_100_EN', 'FRGHT_NTWR', 'DCTT', 'CL

## Processing each column

We need to get each column in a state that's ready for inclusion in this model. This means taking a look at every column to decide if it's worth keeping, converting non-numerial columns to numerical if necessary, and identifying categorical variables for one-hot encoding.

One problem: we've got 176 columns.

In [59]:
print('Columns left:', len(df.columns))
df.columns

Columns left: 176


Index(['FID', 'RIA_RTE_ID', 'RTE_GRID', 'GID', 'FRM_DFO', 'TO_DFO', 'C_SEC',
       'CON', 'SEC', 'BMP', 'EMP', 'RI_MPT_DAT', 'HWY', 'HSYS', 'HNUM', 'HSUF',
       'FRM_NBR', 'FRM_SUF', 'FRM_NUM', 'FRM_DISP', 'TO_NBR', 'TO_SUF',
       'TO_NUM', 'TO_DISP', 'FRM_MKR_DA', 'TO_MKR_DAT', 'DIR_TRAV', 'STE_NAM',
       'DI', 'CO', 'CITY', 'MPA', 'UAN', 'UAN_HPMS', 'RU', 'MSA_CNTY',
       'MAINT_DIS', 'MNT_SEC', 'PBLC_LAND', 'ADMIN', 'RDWAY_MAIN', 'F_SYSTEM',
       'RU_F_SYSTE', 'SEC_NHS', 'SEC_NHS_AP', 'SEC_STR', 'SEC_TRUNK',
       'SEC_TRK', 'SEC_EVAC', 'SEC_NFH', 'SEC_STM', 'SEC_BIC', 'SEC_ADP',
       'SEC_FED_AI', 'MSA_CLS', 'TOP100ID', 'HWY_STAT', 'HWY_STAT_D', 'DOTT',
       'SPD_MAX', 'SPD_MIN', 'ALT_SPD_LM', 'ALT_SPD__1', 'LOAD_AXLE',
       'LOAD_GROSS', 'LOAD_TAND', 'TOLL_NM', 'HWY_DES1', 'ACES_CTRL',
       'BRDG_STRUC', 'MED_TYPE', 'MED_WID', 'HP_MED_W', 'NUM_LANES',
       'CLMB_PS_LA', 'ACCEL_DECE', 'HOV_LANES', 'HOV_TYP', 'ROW_MIN',
       'ROW_W_USL', 'RB_WID', 'SUR_W', 'S

In [60]:
df.dtypes

FID               int64
RIA_RTE_ID       object
RTE_GRID          int64
GID               int64
FRM_DFO         float64
TO_DFO          float64
C_SEC            object
CON             float64
SEC               int64
BMP             float64
EMP             float64
RI_MPT_DAT        int64
HWY              object
HSYS             object
HNUM             object
HSUF             object
FRM_NBR           int64
FRM_SUF          object
FRM_NUM          object
FRM_DISP        float64
TO_NBR            int64
TO_SUF           object
TO_NUM           object
TO_DISP         float64
FRM_MKR_DA        int64
TO_MKR_DAT        int64
DIR_TRAV          int64
STE_NAM          object
DI                int64
CO                int64
CITY              int64
MPA               int64
UAN               int64
UAN_HPMS          int64
RU                int64
MSA_CNTY          int64
MAINT_DIS         int64
MNT_SEC           int64
PBLC_LAND       float64
ADMIN             int64
RDWAY_MAIN        int64
F_SYSTEM        

### TEMP: Reducing columns of analysis

Let's assume that columns that `pandas` has interpreted as floats can be assumed to be important and categorical. (It seems that `pandas` needs to see both decimal points and some variety in inputs to determine that a column is a float.) That leaves us with 140 columns to evaluate.

In [68]:
print('Columns not read as float:', len(df.dtypes[df.dtypes != np.float64]))
df.dtypes[df.dtypes != np.float64]

Columns not read as float: 122


FID             int64
RIA_RTE_ID     object
RTE_GRID        int64
GID             int64
C_SEC          object
SEC             int64
RI_MPT_DAT      int64
HWY            object
HSYS           object
HNUM           object
HSUF           object
FRM_NBR         int64
FRM_SUF        object
FRM_NUM        object
TO_NBR          int64
TO_SUF         object
TO_NUM         object
FRM_MKR_DA      int64
TO_MKR_DAT      int64
DIR_TRAV        int64
STE_NAM        object
DI              int64
CO              int64
CITY            int64
MPA             int64
UAN             int64
UAN_HPMS        int64
RU              int64
MSA_CNTY        int64
MAINT_DIS       int64
MNT_SEC         int64
ADMIN           int64
RDWAY_MAIN      int64
F_SYSTEM        int64
RU_F_SYSTE     object
SEC_NHS         int64
SEC_STR         int64
SEC_TRUNK       int64
SEC_TRK         int64
SEC_EVAC        int64
SEC_NFH         int64
SEC_STM         int64
SEC_BIC         int64
SEC_ADP         int64
SEC_FED_AI      int64
MSA_CLS   

### TEMP: Checking and removing non-numerical columns

Non-numerical columns are likely to be some form of ID and therefore possibly unusable. Let's check each one and pick which ones we want to keep.

If there are a lot of unique values for this nonnumerical column (say, more than 100), that suggests that it's an ID of some sort and safe to remove. 

In [75]:
nonnumcol = df.dtypes[df.dtypes == np.object]
print('Non-numerical columns:', len(nonnumcol))
for col in nonnumcol.index:
    uniques = df[col].unique()
    print('{}\t\t{}'.format(col,len(uniques)))
    if len(uniques)<100:
        print(uniques[0:10])
    print()

Non-numerical columns: 24
RIA_RTE_ID		4586

C_SEC		8904

HWY		4586

HSYS		19
['FM' 'BU' 'BS' 'BI' 'BF' 'RM' 'SH' 'IH' 'PR' 'PA']

HNUM		4002

HSUF		26
[nan 'J' 'B' 'U' 'F' 'S' 'E' 'R' 'V' 'H']

FRM_SUF		4
[nan 'A' 'C' 'B']

FRM_NUM		1027

TO_SUF		4
[nan 'A' 'C' 'B']

TO_NUM		1030

STE_NAM		29
[nan "NAO'CONNOR" 'NAWURZBACH' 'NAJaycee' 'NLoopNA' 'NADeltaNA' 'NACampNA'
 'NAIsland' 'NAMiddle IslandNA' 'WGrande']

RU_F_SYSTE		16
['R5' 'R6' 'U4' 'R4' 'U5' 'U3' 'R3' 'U6' 'R7' 'U2']

TOLL_NM		24
[nan 'IH 45 North (Gulf Freeway) HOV/HOT Lane' 'North Tarrant Express'
 'US 59 (Southwest Freeway) HOV/HOT Lane'
 'US 59 (Eastex Freeway) HOV/HOT Lane' 'LBJ East' 'LBJ Managed Lanes'
 '35Express' 'IH 45 South (Gulf Freeway ) HOV/HOT Lane'
 'US 290 (Northwest Freeway) HOV/HOT Lane']

BRDG_STRUC		838

TRF_STA_ID		30900

RTE_NM		4558

RTE_PRFX		20
['FM' nan 'BU' 'BS' 'BI' 'BF' 'RM' 'SH' 'IH' 'PR']

RTE_NBR		3981

RTE_SFX		26
[nan 'B' 'U' 'F' 'S' 'J' 'E' 'R' 'V' 'H']

RDBD_TYPE		2
['KG' nan]

ASSET_NM		2
[

Cross-referencing with column descriptions, `HSYS` seems to be the only one worth keeping.

In [ ]:
objcolstodel = list(nonnumcol.index)
objcolstodel.remove('HSYS')
cols_dropped += objcolstodel

In [323]:
df.drop(objcolstodel, axis=1, inplace=True)

In [ ]:
cols2onehot = ['HSYS']

### TEMP: Checking and removing integer columns

We've narrowed it down to about 100 columns. There's no easy way to differentiate them so we'll look at each one individually.

In [94]:
cols = list(df.dtypes[df.dtypes == np.int64].index)
print('Integer columns:', len(cols))

Integer columns: 98


In [197]:
def check_col(colname):
    uniques = df[colname].unique()
    print('{}\t\t{}'.format(colname,len(uniques)))
    print(uniques[0:10])

def drop_col(colname):
    df.drop(colname, axis=1, inplace=True)
    cols_dropped.append(colname)

In [102]:
check_col(cols[0])

FID		156451
[0 1 2 3 4 5 6 7 8 9]


ID for each data point. Keep.

In [ ]:
check_col(cols[1])

Don't know what this is. Values look very similar. Discard.

In [113]:
drop_col(cols[1])

In [116]:
check_col(cols[2])

GID		5563
[3134 3090 3038 3014 3145 3075 3168 3139 3138 3005]


In [117]:
drop_col(cols[2])

In [118]:
check_col(cols[3])

SEC		25
[ 3  2  9  1  4 11  5  6 15 14]


Notes don't suggest that SEC has any real meaning. Discard.

In [120]:
drop_col(cols[3])

In [121]:
check_col(cols[4])

RI_MPT_DAT		25
[201505 201710 201711 201701 201801 201704 201705 201802 201712 201804]


In [122]:
drop_col(cols[4])

In [123]:
check_col(cols[5])

FRM_NBR		908
[418 416 324 556 516 550 470 548 512 652]


In [124]:
drop_col(cols[5])

In [125]:
check_col(cols[6])

TO_NBR		911
[418 416 324 556 516 550 472 548 514 654]


In [126]:
drop_col(cols[6])

In [127]:
check_col(cols[7])

FRM_MKR_DA		168
[20150512 20180430 20161116 20160407 20160302 20160725 20170406 20170428
 20170508 20171223]


In [128]:
drop_col(cols[7])

In [129]:
check_col(cols[8])

TO_MKR_DAT		169
[20150512 20180430 20161116 20160407 20160302 20160725 20170406 20170428
 20170508 20171223]


In [130]:
drop_col(cols[8])

In [131]:
check_col(cols[9])

DIR_TRAV		4
[1 4 0 3]


The values here are outside the range detailed by supporting documentation. Discard.

In [132]:
drop_col(cols[9])

In [133]:
check_col(cols[10])

DI		25
[14 23 15 12 16 21 22 25 18 20]


Says which district the data's from. Unlikely to be predictive and would add many columns via one-hot encoding. Discard.

In [198]:
drop_col(cols[10])

In [134]:
check_col(cols[11])

CO		254
[246  25 247  20 205 167 125 142 162  13]


Same as above.

In [199]:
drop_col(cols[11])

In [135]:
check_col(cols[12])

CITY		1139
[41900     0 30750 33750 11800  1200 29300 16450 19350 25150]


Same as above.

In [200]:
drop_col(cols[12])

In [136]:
check_col(cols[13])

MPA		26
[ 90   0  15 282 211 277 166 363 135 230]


Same as above.

In [201]:
drop_col(cols[13])

In [137]:
check_col(cols[14])

UAN		187
[  0 459 250  15 282 465 230 669 139 616]


Same as above.

In [ ]:
drop_col(cols[14])

In [139]:
check_col(cols[15])

UAN_HPMS		187
[    0 46801 87220 40429 22042 52687 52390 39781 70993  9973]


Same as above.

In [203]:
drop_col(cols[15])

In [141]:
check_col(cols[16])

RU		4
[1 3 4 2]


A good feature that determines how urbanized a city is. And continuous. Kept.

In [143]:
check_col(cols[17])

MSA_CNTY		2
[1 0]


Categorical. Whether a road is in an MSA county probably isn't super predictive, but no harm in keeping it. Already one-hot too.

In [144]:
check_col(cols[18])

MAINT_DIS		26
[14 23 15 12 16 21 22 25 18 20]


Maintenance district would add many columns for one-hot and is unlikely to be predictive. Discard.

In [204]:
drop_col(cols[18])

In [145]:
check_col(cols[19])

MNT_SEC		23
[13  1  4  2 10  7  3 14  6  9]


Same as above.

In [205]:
drop_col(cols[19])

In [146]:
check_col(cols[20])

ADMIN		2
[1 0]


Already one-hot. Keep.

In [170]:
check_col(cols[21])

RDWAY_MAIN		4
[ 1  0 16  4]


No documentation for this. Discard.

In [171]:
drop_col(cols[21])

In [172]:
check_col(cols[22])

F_SYSTEM		8
[5 6 4 3 7 2 1 0]


Same as above.

In [173]:
drop_col(cols[22])

In [174]:
check_col(cols[23])

SEC_NHS		9
[0 1 8 9 6 2 7 3 5]


Keep. Categorical.

In [209]:
cols2onehot.append(cols[23])

In [177]:
check_col(cols[24])

SEC_STR		3
[0 1 2]


Documentation says this should only have two values. Drop.

In [181]:
drop_col(cols[24])

In [179]:
check_col(cols[25])

SEC_TRUNK		4
[0 1 3 2]


Same as above.

In [182]:
drop_col(cols[25])

In [183]:
check_col(cols[26])

SEC_TRK		3
[0 2 1]


Is this the same as above? Discard

In [184]:
drop_col(cols[26])

In [186]:
check_col(cols[27])

SEC_EVAC		2
[0 1]


Categorical. Whether a road is an evac route probably isn't super predictive, but no harm in keeping it. It's a binary variable so no need to one-hot it either.

In [188]:
check_col(cols[28])

SEC_NFH		2
[0 1]


Same as above.

In [190]:
check_col(cols[29])

SEC_STM		2
[0 1]


Same as above.

In [211]:
check_col(cols[30])

SEC_BIC		2
[0 1]


Same as above.

In [215]:
check_col(cols[31])

SEC_ADP		2
[0 1]


Same as above.

In [216]:
check_col(cols[32])

SEC_FED_AI		2
[1 0]


Same as above.

In [217]:
check_col(cols[33])

MSA_CLS		3
[11 12 13]


Documentation says 11-13 all mean the same thing. Discard.

In [218]:
drop_col(cols[33])

In [219]:
check_col(cols[34])

HWY_STAT		2
[6 0]


Keep. Already one-hot.

In [220]:
check_col(cols[35])

HWY_STAT_D		716
[19950429 19980603 19960520 19961126 20131219 19980501 20040809 20110128
 20071219 19961122]


Dates. Discard.

In [221]:
drop_col(cols[35])

In [222]:
check_col(cols[36])

DOTT		726
[19950429 19980603 19960520 19961126 20131219 19980501 20040809 20110128
 20071219 19961122]


Same as above.

In [223]:
drop_col(cols[36])

In [224]:
check_col(cols[37])

SPD_MAX		18
[60 55 30 65 45 70 40 50 35 75]


Continuous.

In [225]:
check_col(cols[38])

SPD_MIN		2
[ 0 55]


Same as above.

In [226]:
check_col(cols[39])

LOAD_AXLE		4
[    0 12000  4000  8000]


Same as above.

In [227]:
check_col(cols[40])

LOAD_GROSS		3
[    0 58420 40000]


Same as above.

In [228]:
check_col(cols[41])

LOAD_TAND		2
[    0 14000]


Same as above.

In [229]:
check_col(cols[42])

HWY_DES1		6
[2 3 5 4 0 1]


Highway characteristic. Very important! Categorical!

In [231]:
cols2onehot.append(cols[42])

In [230]:
check_col(cols[43])

ACES_CTRL		4
[3 1 2 0]


Not documented. Drop.

In [235]:
drop_col(cols[43])

In [233]:
check_col(cols[44])

MED_TYPE		8
[ 0  2  3  4 99  7  5  6]


Highway characteristic. Very important! Categorical!

In [236]:
cols2onehot.append(cols[44])

In [237]:
check_col(cols[45])

MED_WID		180
[ 0 14 44 75 20 10 16 15  4 21]


Highway characteristic. Very important! But continuous.

In [238]:
check_col(cols[46])

HP_MED_W		247
[ 1  2  6  8  4 10  3  0  5 18]


Same as above.

In [239]:
check_col(cols[47])

NUM_LANES		15
[ 2  4  6  3  5  8  7  1 10 11]


Same as above.

In [240]:
check_col(cols[48])

ACCEL_DECE		2
[0 1]


Not documented. Drop.

In [242]:
drop_col(cols[48])

In [243]:
check_col(cols[49])

HOV_TYP		2
[0 1]


Highway characteristic. Very important! But continuous.

In [244]:
check_col(cols[50])

ROW_MIN		401
[ 80 100  70 120  57 200 112  60 107 300]


Same as above.

In [245]:
check_col(cols[51])

ROW_W_USL		412
[ 80 100  70 120  57 200 112  60 107 300]


Same as above.

In [246]:
check_col(cols[52])

RB_WID		202
[22 24 36 40 32 44 30 28 48 20]


Same as above.

In [247]:
check_col(cols[53])

SUR_W		164
[20 24 18 30 28 26 48 22 23 51]


Same as above.

In [248]:
check_col(cols[54])

S_TYPE_I		7
[ 3  5  1  4  0  2 99]


Highway characteristic. Very important! Categorical. 99 and 0 shouldn't be within scope but whatever.

In [250]:
cols2onehot.append(cols[54])

In [249]:
check_col(cols[55])

S_WID_I		46
[ 1  2  6  8  4 10  3  0  5 20]


Highway characteristic. Very important! But continuous.

In [251]:
check_col(cols[56])

S_USE_I		8
[5 0 2 1 7 6 3 4]


Highway characteristic. Very important! Categorical.

In [255]:
cols2onehot.append(cols[56])

In [252]:
check_col(cols[57])

S_TYPE_O		7
[ 3  5  1  4  0  2 99]


Same as above.

In [258]:
cols2onehot.append(cols[57])

In [253]:
check_col(cols[58])

S_WID_O		43
[ 1  2  6  8 10  4  3  0  5 14]


Highway characteristic. Very important! But continuous.

In [254]:
check_col(cols[59])

S_USE_O		8
[5 0 2 1 6 3 4 7]


Highway characteristic. Very important! Categorical.

In [256]:
cols2onehot.append(cols[59])

In [259]:
check_col(cols[60])

CURB_L		6
[0 2 1 5 4 3]


Same as above.

In [260]:
cols2onehot.append(cols[60])

In [261]:
check_col(cols[61])

CURB_R		6
[0 2 1 5 4 3]


Same as above.

In [262]:
cols2onehot.append(cols[61])

In [263]:
check_col(cols[62])

BASE_TP		11
[14  7  6  1 11  9 10  0  4  3]


Same as above.

In [264]:
cols2onehot.append(cols[62])

In [265]:
check_col(cols[63])

SRF_TYPE		12
[10  4  1  2  7  5  6  3 11 13]


Same as above.

In [266]:
cols2onehot.append(cols[63])

In [267]:
check_col(cols[64])

SURF_TREAT		8
[1 5 2 0 7 8 9 4]


Same as above.

In [268]:
cols2onehot.append(cols[64])

In [269]:
check_col(cols[65])

ADT_CUR		12885
[1008  128  692 7799 1858  260 1094 7505  274 1313]


This is the average daily traffic. Keep unless we think it's not infrastructure-related. Continuous.

In [270]:
check_col(cols[66])

ADT_ADJ		12885
[1008  128  692 7799 1858  260 1094 7505  274 1313]


Same as above.

In [271]:
check_col(cols[67])

D_FAC		51
[53 54 67 50 51 74 60 56 72 62]


Directional factor? Continuous. Keep I guess?

In [272]:
check_col(cols[68])

AADT_TRUCK		4456
[101  17 346 179 208  39 457 173  14 358]


This is the average daily traffic for trucks. Keep unless we think it's not infrastructure-related. Continuous.

In [273]:
check_col(cols[69])

AADT_SINGL		2298
[ 47   5 164 148 154  34 217 143  12 101]


Same but for single unit vehicles. Keep.

In [274]:
check_col(cols[70])

AADT_COMBI		3718
[ 54  12 182  31   5 240  30   2 257 223]


Same but for both(?). How is this different from AADT? Keep.

In [275]:
check_col(cols[71])

FLEX_ESAL		8908
[ 345   73 1496  577  472   69 1980  522   29 1492]


Equivalent single axle load. Keep.

In [276]:
check_col(cols[72])

RIGID_ESAL		10301
[ 450  102 2101  728  613   85 2780  658   33 2081]


Same as above.

In [277]:
check_col(cols[73])

ATH_100		105
[ 43  47 101  32  48  50  90  33  68  92]


Average of the Ten Heaviest Wheel Loads. Keep.

In [278]:
check_col(cols[74])

ATH_PCT		7
[40 30 20 50 60  0 10]


Same as above, but in percentages?

In [279]:
check_col(cols[75])

MOTORCYCLE		418
[ 5  0 34  7  1 32 84 36  6  2]


No documentation. Discard.

In [282]:
drop_col(cols[75])

In [ ]:
check_col(cols[76])

Annual daily traffic in year 1. Redundant, discard.

In [280]:
drop_col(cols[76])

In [283]:
check_col(cols[77])

HY_2		12614
[1002   97  653 6615 2085  188 1144 7162  409 2346]


Annual daily traffic in year 2. Redundant, discard.

In [284]:
drop_col(cols[77])

In [285]:
check_col(cols[78])

HY_3		12395
[ 953   87 1015 4697 1708  197 1812 5468  290 1360]


Annual daily traffic in year 3. Redundant, discard.

In [286]:
drop_col(cols[78])

In [287]:
check_col(cols[79])

HY_4		12303
[ 822  136 1094 5227 1597  217 1754 5388  363 3457]


In [288]:
check_col(cols[80])

HY_5		2167
[ 760  150  800 5500 1800  290 1550 5200  350 2000]


In [289]:
check_col(cols[81])

HY_6		1511
[ 590  120  720 5500 1950  260 1450 6200  350 1300]


In [290]:
check_col(cols[82])

HY_7		1473
[ 590  130  550 5000 2000  230 1200 5200    0  270]


In [291]:
check_col(cols[83])

HY_8		1447
[ 670  120  590 5900 1900  230 1400  640  440    0]


In [292]:
check_col(cols[84])

HY_9		1447
[ 650  120  510 6400 1700  220 1250  600  610    0]


Annual daily traffic in year 4-9. Redundant, discard.

In [299]:
for i in range(79,85):
    drop_col(cols[i])

In [293]:
check_col(cols[85])

AADT_DESGN		5030
[ 1410   180   970 12640  2600   330  1530 10810   380  1840]


AADT for design year. Keep. Continuous.

In [301]:
check_col(cols[86])

INCRS_FC_1		8445
[ 402   52  278 4841  742   70  436 3305  106  527]


No documentation. Discard.

In [302]:
drop_col(cols[86])

In [303]:
check_col(cols[87])

DHV		4860
[ 149   22  119 1454  286   50  228 1276   40  162]


Design hourly volume. Keep. Continuous.

In [304]:
check_col(cols[88])

HP_VOL_GRP		12
[ 2  1  4  5  6  3  7  8 11 10]


Highway performance monitoring system volume group. Continuous?

In [305]:
check_col(cols[89])

LANE_WIDTH		43
[10 12 13 11  9 25 15 14 31 16]


Not documented but self-explanatory. Continuous.

In [306]:
check_col(cols[90])

Crash Count		383
[ 0  2  1 10  3  5  4  6  7 11]


This is what we calculated.

In [307]:
check_col(cols[91])

Avg_Month		1262
[ 0  8  2 12 68 18  1  9 19 28]


Same as above but monthly.

In [308]:
check_col(cols[92])

FID_2		16347
[2011 2019 2024 2032 2048 2052 2061 2072 2082 2088]


In [309]:
check_col(cols[93])

OBJECTID_1		16347
[3012 3020 3025 3033 3049 3053 3062 3073 3083 3089]


Some ID or something. Discard.

In [310]:
drop_col(cols[93])

In [311]:
check_col(cols[94])

GID_1		5522
[3134 3090 3038 3014 3145 3075 3168 3139 3138 3005]


Same as above.

In [312]:
check_col(cols[95])

SPD_LMT		18
[60 55 30 65 45 70 40 50 35 75]


Seems like a duplicate of `spd_max`. Discard.

In [314]:
drop_col(cols[95])

In [313]:
check_col(cols[96])

ASSET_ID		16347
[5577085 5577094 5577099 5577108 5577127 5577132 5577141 5577152 5577162
 5577169]


Some ID or something. Discard.

In [315]:
drop_col(cols[96])

In [316]:
check_col(cols[97])

MAX_SPD_LM		18
[60 55 30 65 45 70 40 50 35 75]


Seems like a duplicate of `spd_max` too(?). Discard.

In [317]:
drop_col(cols[97])

That's all of them.

### Results of filtering

In [319]:
cols_dropped

['FID_1',
 'FID_1_1',
 'OBJECTID',
 'REC',
 'RDBD_ID',
 'SEC_TTT',
 'SEC_PARK',
 'TOP_100_BE',
 'TOP_100_EN',
 'FRGHT_NTWR',
 'DCTT',
 'CLSR_RESN',
 'HWY_NOTE',
 'SCHOOL_ZN',
 'DBTP',
 'PEAK_DRCT_',
 'CAUSEWAY',
 'TUNNEL',
 'MULT_MOD_F',
 'ADT_YEAR',
 'ADT_HIST_Y',
 'DESGN_YR',
 'TRUCK_HY_1',
 'TRUCK_HY_2',
 'TRUCK_HY_3',
 'TRUCK_HY_4',
 'TRUCK_HY_5',
 'TRUCK_HY_6',
 'TRUCK_HY_7',
 'TRUCK_HY_8',
 'TRUCK_HY_9',
 'B_TERM',
 'E_TERM',
 'PHY_RDBD',
 'PEAK_LANE',
 'CNTR_PEAK_',
 'TRFC_SGNL',
 'PCT_GREEN_',
 'NBR_SGNL',
 'NBR_STOP_S',
 'ATGRD_OTHR',
 'WIDE_OBST',
 'WIDE_PTNTL',
 'CURV_CLASS',
 'CURV_CLA_1',
 'CURV_CLA_2',
 'CURV_CLA_3',
 'CURV_CLA_4',
 'CURV_CLA_5',
 'VERT_GRADE',
 'VERT_GRA_1',
 'VERT_GRA_2',
 'VERT_GRA_3',
 'VERT_GRA_4',
 'VERT_GRA_5',
 'TRRN',
 'PPSD',
 'PSR',
 'PSR_DT',
 'RUTTING',
 'FAULT',
 'CRACK_PCT',
 'CRACK_LNGT',
 'CLMT_ZN',
 'SOIL',
 'LOC_ERROR',
 'RIA_RTE_ID',
 'C_SEC',
 'HWY',
 'HNUM',
 'HSUF',
 'FRM_SUF',
 'FRM_NUM',
 'TO_SUF',
 'TO_NUM',
 'STE_NAM',
 'RU_F_SY

In [328]:
cols2onehot

['SEC_NHS',
 'HWY_DES1',
 'MED_TYPE',
 'S_TYPE_I',
 'S_USE_I',
 'S_USE_O',
 'S_TYPE_O',
 'CURB_L',
 'CURB_R',
 'BASE_TP',
 'SRF_TYPE',
 'SURF_TREAT',
 'HSYS']

## One-hot encoding

Now that we've identified columns that require one-hot encoding, let's do so after we check that all our remaining columns are numerical.

In [329]:
df.dtypes

FID               int64
FRM_DFO         float64
TO_DFO          float64
CON             float64
BMP             float64
EMP             float64
HSYS              int64
FRM_DISP        float64
TO_DISP         float64
RU                int64
MSA_CNTY          int64
PBLC_LAND       float64
ADMIN             int64
SEC_NHS           int64
SEC_NHS_AP      float64
SEC_EVAC          int64
SEC_NFH           int64
SEC_STM           int64
SEC_BIC           int64
SEC_ADP           int64
SEC_FED_AI        int64
TOP100ID        float64
HWY_STAT          int64
SPD_MAX           int64
SPD_MIN           int64
ALT_SPD_LM      float64
ALT_SPD__1      float64
LOAD_AXLE         int64
LOAD_GROSS        int64
LOAD_TAND         int64
HWY_DES1          int64
MED_TYPE          int64
MED_WID           int64
HP_MED_W          int64
NUM_LANES         int64
CLMB_PS_LA      float64
HOV_LANES       float64
HOV_TYP           int64
ROW_MIN           int64
ROW_W_USL         int64
RB_WID            int64
SUR_W           

In [346]:
for col in cols2onehot:
    df = pd.concat([df, pd.get_dummies(df[col], prefix=col, dummy_na=df[col].isna().any())], axis=1)
    df.drop(col, axis=1, inplace=True)
df.head()

FID  FRM_DFO  TO_DFO     CON     BMP     EMP  FRM_DISP  TO_DISP  RU  \
0    0    4.764   4.957   986.0   4.783   4.977     0.764    0.957   1   
1    1    3.708   3.729   986.0   3.723   3.744     1.708    1.729   1   
2    2    9.283   9.287  1033.0   7.816   7.820     1.805    1.809   1   
3    3   34.630  34.648   366.0   9.415   9.433     1.905    1.923   1   
4    4   12.785  12.814  1003.0  15.007  15.036     1.072    1.101   3   

   MSA_CNTY  PBLC_LAND  ADMIN  SEC_NHS_AP  SEC_EVAC  SEC_NFH  SEC_STM  \
0         1        NaN      1         NaN         0        0        0   
1         1        NaN      1         NaN         0        0        0   
2         0        NaN      1         NaN         0        0        0   
3         1        NaN      1         NaN         0        0        0   
4         1        NaN      1         NaN         1        0        0   

   SEC_BIC  SEC_ADP  SEC_FED_AI  TOP100ID  HWY_STAT  SPD_MAX  SPD_MIN  \
0        0        0           1       NaN         6       60        0   
1        0        0           1       NaN         6       60        0   
2        0        0           0       NaN         6       60        0   
3        0        0           1       NaN         6       55        0   
4        0        0           1       NaN         6       60        0   

   ALT_SPD_LM  ALT_SPD__1  LOAD_AXLE  LOAD_GROSS  LOAD_TAND  MED_WID  \
0         NaN         NaN          0           0          0        0   
1         NaN         NaN          0           0          0        0   
2         NaN         NaN          0           0          0        0   
3         NaN         NaN          0       58420          0        0   
4         NaN         NaN          0           0          0        0   

   HP_MED_W  NUM_LANES  CLMB_PS_LA  HOV_LANES  HOV_TYP  ROW_MIN  ROW_W_USL  \
0         1          2         NaN        NaN        0       80         80   
1         1          2         NaN        NaN        0       80         80   
2         2          2         NaN        NaN        0      100        100   
3         6          2         NaN        NaN        0      100        100   
4         8          2         NaN        NaN        0      100        100   

   RB_WID  SUR_W  S_WID_I  S_WID_O  SURF_TRE_1  SURF_TRE_2  ADT_CUR  ADT_ADJ  \
0      22     20        1        1         0.0         NaN     1008     1008   
1      22     20        1        1         0.0         NaN     1008     1008   
2      24     20        2        2         0.0         NaN      128      128   
3      36     24        6        6         0.0         NaN      692      692   
4      40     24        8        8         0.0         NaN     7799     7799   

   K_FAC  D_FAC  TRK_AADT_P  PCT_SADT  PCT_CADT  AADT_TRUCK  AADT_SINGL  \
0   10.6     53        10.1       4.7       5.4         101          47   
1   10.6     53        10.1       4.7       5.4         101          47   
2   12.5     54        13.3       3.9       9.4          17           5   
3   12.3     67        50.0      23.7      26.3         346         164   
4   11.5     50         2.3       1.9       0.4         179         148   

   AADT_COMBI  TRK_DHV_PC  PCT_SDHV  PCT_CDHV  FLEX_ESAL  RIGID_ESAL  ATH_100  \
0          54         4.7       2.6       2.1        345         450       43   
1          54         4.7       2.6       2.1        345         450       43   
2          12        14.5       1.9      12.6         73         102       47   
3         182        37.2      18.2      19.0       1496        2101      101   
4          31         0.8       0.6       0.2        577         728       32   

   ATH_PCT  AADT_DESGN  INCRS_FCTR   DHV  HPMSID  HP_VOL_GRP  RT_TURN_LA  \
0       40        1410         1.7   149     NaN           2         NaN   
1       40        1410         1.7   149     NaN           2         NaN   
2       40         180         1.7    22     NaN           1         NaN   
3       30         970         1.7   119     NaN       

In [348]:
len(df.columns)

213

## Replace `NaN` values

With 0 because (at least for many cases like `RT_TURN_LA`) that implies zero of the item (in this case, right turn lanes).

In [350]:
df.fillna(0, inplace=True)

## Calculate crash rate

Raw yearly crash count / (average daily traffic * days in year * length of section). Set to zero if either average daily traffic or length of section are 0.

In [362]:
df['Crash_rate'] = df['Crash Count']/(df['ADT_ADJ'] * 365 * df['LEN_SEC'])
df.loc[df['Crash_rate']==np.inf,'Crash_rate'] = 0
df.head()

## Split into training and test sets, remove extraneous data, and export

TODO
1. Remove `Crash Count`, `Avg_Death`, and `Avg_Injuries`
2. Split into training and test sets
3. Build X_with_ID and Y_with_ID dataframes out of both training and test sets
4. Export a total of 4 dataframes

In [366]:
train_ids = np.random.rand(len(df)) < 0.9
df[train_ids].to_csv('processed/training.csv', index=False)
df[~train_ids].to_csv('processed/test.csv', index=False)